site_name: Fiware-iotagent-ul
site_url: https://fiware-iotagent-ul.readthedocs.org
repo_url: https://github.com/telefonicaid/iotagent-ul
site_description: IoT Agent Ultralight2.0 (HTTP or MQTT) Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css", "https://fiware.org/style/fiware_readthedocs_iot.css"]
pages:
  - Home: 'index.md'
  - 'User & Programmers Manual':
    - 'API Walkthrough & Development intro': 'usermanual.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
    - 'Operations (logs & alarms)': 'operations.md'
    
